<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class InstitutionSeeder extends Seeder
{
    public function run(): void
    {
        $institutions = [
            [
                'name' => 'Stanford University',
                'description' => 'Один из ведущих частных исследовательских университетов мира, расположенный в Кремниевой долине.',
                'country' => 'США',
                'city' => 'Stanford',
                'type' => 'university',
                'image_url' => 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.8,
                'featured' => true,
                'programs' => json_encode(['Информационные технологии', 'Бизнес', 'Инженерия', 'Медицина']),
                'price_from' => 55000,
                'price_to' => 75000,
                'currency' => 'USD',
                'views' => 1250,
            ],
            [
                'name' => 'MIT',
                'description' => 'Массачусетский технологический институт - мировой лидер в области науки и технологий.',
                'country' => 'США',
                'city' => 'Cambridge',
                'type' => 'university',
                'image_url' => 'https://tse1.mm.bing.net/th/id/OIP.qY0g0xauaMpU1qlrVwMMswHaE7?rs=1&pid=ImgDetMain&o=7&rm=3',
                'rating' => 4.9,
                'featured' => true,
                'programs' => json_encode(['Информационные технологии', 'Инженерия', 'Бизнес']),
                'price_from' => 53000,
                'price_to' => 72000,
                'currency' => 'USD',
                'views' => 1850,
            ],
            [
                'name' => 'Harvard University',
                'description' => 'Старейший университет США, входящий в Лигу плюща.',
                'country' => 'США',
                'city' => 'Cambridge',
                'type' => 'university',
                'image_url' => 'https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.9,
                'featured' => true,
                'programs' => json_encode(['Бизнес', 'Медицина', 'Информационные технологии']),
                'price_from' => 58000,
                'price_to' => 78000,
                'currency' => 'USD',
                'views' => 2100,
            ],
            [
                'name' => 'University of Tokyo',
                'description' => 'Ведущий исследовательский университет Японии, известный своими научными достижениями.',
                'country' => 'Япония',
                'city' => 'Tokyo',
                'type' => 'university',
                'image_url' => 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.6,
                'featured' => false,
                'programs' => json_encode(['Инженерия', 'Информационные технологии']),
                'price_from' => 4500,
                'price_to' => 8500,
                'currency' => 'USD',
                'views' => 890,
            ],
            [
                'name' => 'Kyoto University',
                'description' => 'Второй по старшинству университет Японии, известный исследованиями в области физики и химии.',
                'country' => 'Япония',
                'city' => 'Kyoto',
                'type' => 'university',
                'image_url' => 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.5,
                'featured' => true,
                'programs' => json_encode(['Медицина', 'Инженерия']),
                'price_from' => 4200,
                'price_to' => 8000,
                'currency' => 'USD',
                'views' => 750,
            ],
            [
                'name' => 'Tokyo Galaxy Japanese Language School',
                'description' => 'Tokyo Galaxy Japanese Language School предлагает различные курсы обучения, факультативные занятия, эффективные методики и качественные учебные материалы. Обучение строится в зависимости от целей студента и его уровня образования и владения японским языком. Tokyo Galaxy Japanese Language School - одна из лучших вариантов в Токио для комфортного и эффективного изучения японского языка, а также, дальнейшего образования и трудоустройства.',
                'country' => 'Япония',
                'city' => 'Tokyo',
                'type' => 'Language School',
                'image_url' => 'https://study-japan-guide.com/media/images/TOKYO%20GALAXY-2.jpg',
                'rating' => 4.9,
                'featured' => true,
                'programs' => json_encode(['Языковые курсы']),
                'price_from' => 4200,
                'price_to' => 8000,
                'currency' => 'USD',
                'views' => 900,
            ],
            [
                'name' => 'University of Oxford',
                'description' => 'Старейший англоязычный университет в мире, основанный в 1096 году.',
                'country' => 'Великобритания',
                'city' => 'Oxford',
                'type' => 'university',
                'image_url' => 'https://images.unsplash.com/photo-1519070990762-3f6c7e4a2cb0?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.7,
                'featured' => true,
                'programs' => json_encode(['Бизнес', 'Медицина', 'Информационные технологии']),
                'price_from' => 25000,
                'price_to' => 45000,
                'currency' => 'GBP',
                'views' => 1650,
            ],
            [
                'name' => 'Imperial College London',
                'description' => 'Ведущий мировой университет в области науки, инженерии, медицины и бизнеса.',
                'country' => 'Великобритания',
                'city' => 'London',
                'type' => 'university',
                'image_url' => 'https://images.unsplash.com/photo-1542744095-fcf48d80b0fd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.7,
                'featured' => false,
                'programs' => json_encode(['Инженерия', 'Медицина', 'Информационные технологии']),
                'price_from' => 32000,
                'price_to' => 48000,
                'currency' => 'GBP',
                'views' => 1420,
            ],
            [
                'name' => 'University of Toronto',
                'description' => 'Ведущий государственный исследовательский университет Канады.',
                'country' => 'Канада',
                'city' => 'Toronto',
                'type' => 'university',
                'image_url' => 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.6,
                'featured' => true,
                'programs' => json_encode(['Информационные технологии', 'Бизнес', 'Медицина']),
                'price_from' => 28000,
                'price_to' => 52000,
                'currency' => 'CAD',
                'views' => 1320,
            ],
            [
                'name' => 'University of British Columbia',
                'description' => 'Исследовательский университет мирового класса, расположенный в Ванкувере.',
                'country' => 'Канада',
                'city' => 'Vancouver',
                'type' => 'university',
                'image_url' => 'https://images.unsplash.com/photo-1589519160732-57fc498494f8?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.5,
                'featured' => false,
                'programs' => json_encode(['Инженерия', 'Бизнес']),
                'price_from' => 26000,
                'price_to' => 50000,
                'currency' => 'CAD',
                'views' => 980,
            ],

            // Австралия
            [
                'name' => 'University of Sydney',
                'description' => 'Первый университет Австралии, основанный в 1850 году.',
                'country' => 'Австралия',
                'city' => 'Sydney',
                'type' => 'university',
                'image_url' => 'https://images.unsplash.com/photo-1589519160732-57fc498494f8?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.5,
                'featured' => false,
                'programs' => json_encode(['Бизнес', 'Медицина', 'Информационные технологии']),
                'price_from' => 35000,
                'price_to' => 55000,
                'currency' => 'AUD',
                'views' => 1100,
            ],
            [
                'name' => 'University of Melbourne',
                'description' => 'Ведущий исследовательский университет Австралии, известный высоким качеством образования.',
                'country' => 'Австралия',
                'city' => 'Melbourne',
                'type' => 'university',
                'image_url' => 'https://images.unsplash.com/photo-1541339907198-e08756dedf3f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.6,
                'featured' => true,
                'programs' => json_encode(['Инженерия', 'Медицина', 'Бизнес']),
                'price_from' => 38000,
                'price_to' => 58000,
                'currency' => 'AUD',
                'views' => 1250,
            ],

            // Дополнительные учреждения разных типов
            [
                'name' => 'Tokyo Institute of Technology',
                'description' => 'Ведущий национальный университет Японии, специализирующийся на науке и технологиях.',
                'country' => 'Япония',
                'city' => 'Tokyo',
                'type' => 'college',
                'image_url' => 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.4,
                'featured' => false,
                'programs' => json_encode(['Информационные технологии', 'Инженерия']),
                'price_from' => 4000,
                'price_to' => 7500,
                'currency' => 'USD',
                'views' => 620,
            ],
            [
                'name' => 'California Institute of Technology',
                'description' => 'Небольшой частный исследовательский университет в Пасадене, Калифорния.',
                'country' => 'США',
                'city' => 'Pasadena',
                'type' => 'university',
                'image_url' => 'https://images.unsplash.com/photo-1519452639340-ef40a2c3d0a2?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.8,
                'featured' => true,
                'programs' => json_encode(['Инженерия', 'Информационные технологии']),
                'price_from' => 56000,
                'price_to' => 76000,
                'currency' => 'USD',
                'views' => 1450,
            ],
            [
                'name' => 'University of Cambridge',
                'description' => 'Исследовательский университет в Кембридже, Англия, основанный в 1209 году.',
                'country' => 'Великобритания',
                'city' => 'Cambridge',
                'type' => 'university',
                'image_url' => 'https://images.unsplash.com/photo-1519070990762-3f6c7e4a2cb0?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.8,
                'featured' => true,
                'programs' => json_encode(['Медицина', 'Инженерия', 'Бизнес']),
                'price_from' => 27000,
                'price_to' => 46000,
                'currency' => 'GBP',
                'views' => 1780,
            ],
            [
                'name' => 'McGill University',
                'description' => 'Государственный исследовательский университет в Монреале, Квебек, Канада.',
                'country' => 'Канада',
                'city' => 'Montreal',
                'type' => 'university',
                'image_url' => 'https://images.unsplash.com/photo-1542744095-fcf48d80b0fd?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.5,
                'featured' => false,
                'programs' => json_encode(['Медицина', 'Информационные технологии']),
                'price_from' => 29000,
                'price_to' => 53000,
                'currency' => 'CAD',
                'views' => 1120,
            ],
            [
                'name' => 'Australian National University',
                'description' => 'Государственный исследовательский университет в Канберре, столице Австралии.',
                'country' => 'Австралия',
                'city' => 'Canberra',
                'type' => 'university',
                'image_url' => 'https://images.unsplash.com/photo-1589519160732-57fc498494f8?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&q=80',
                'rating' => 4.6,
                'featured' => true,
                'programs' => json_encode(['Информационные технологии', 'Бизнес']),
                'price_from' => 36000,
                'price_to' => 56000,
                'currency' => 'AUD',
                'views' => 1050,
            ],
        ];

        $now = now();
        foreach ($institutions as &$institution) {
            $institution['created_at'] = $now;
            $institution['updated_at'] = $now;
        }

        DB::table('institutions')->insert($institutions);
    }
}
