version: '3.8'

services:
    php:
        build: .
        container_name: studygate-php-8.3
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        extra_hosts:
            - "host.docker.internal:host-gateway"
